""" added attributes for the etl jobs model

Revision ID: 008ff5192eee
Revises: 9fc38b4bf05c
Create Date: 2026-04-24 15:08:31.705696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008ff5192eee'
down_revision = '9fc38b4bf05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etl_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows_processed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rows_inserted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rows_skipped', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etl_jobs', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('error_message')
        batch_op.drop_column('rows_skipped')
        batch_op.drop_column('rows_inserted')
        batch_op.drop_column('rows_processed')

    # ### end Alembic commands ###
