"""Add nom and prenom columns to users table

Revision ID: 03fa2f3a57f9
Revises: 32378c0dd03d
Create Date: 2026-04-17 19:53:23.276572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fa2f3a57f9'
down_revision = '32378c0dd03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
