"""add accidents_raw table

Revision ID: 32378c0dd03d
Revises: 5fd5ebebde5f
Create Date: 2026-04-06 09:47:07.273138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32378c0dd03d'
down_revision = '5fd5ebebde5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accident_id', sa.String(length=100), nullable=True),
    sa.Column('start_time_raw', sa.String(length=50), nullable=True),
    sa.Column('end_time_raw', sa.String(length=50), nullable=True),
    sa.Column('city_raw', sa.String(length=100), nullable=True),
    sa.Column('state_raw', sa.String(length=50), nullable=True),
    sa.Column('severity_raw', sa.Integer(), nullable=True),
    sa.Column('temperature_raw', sa.Float(), nullable=True),
    sa.Column('visibility_raw', sa.Float(), nullable=True),
    sa.Column('weather_condition_raw', sa.String(length=100), nullable=True),
    sa.Column('latitude_raw', sa.Float(), nullable=True),
    sa.Column('longitude_raw', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accidents_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accidents_raw_accident_id'), ['accident_id'], unique=False)

    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accidents_clean_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_accidents_clean_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_accidents_clean_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_accidents_clean_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accidents_clean_state'))
        batch_op.drop_index(batch_op.f('ix_accidents_clean_start_time'))
        batch_op.drop_index(batch_op.f('ix_accidents_clean_severity'))
        batch_op.drop_index(batch_op.f('ix_accidents_clean_city'))

    with op.batch_alter_table('accidents_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accidents_raw_accident_id'))

    op.drop_table('accidents_raw')
    # ### end Alembic commands ###
