"""adding recover password to user model

Revision ID: 5e6935bd55dd
Revises: ffa370c220bf
Create Date: 2026-05-05 15:31:28.061924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6935bd55dd'
down_revision = 'ffa370c220bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_accident_id_clean'), type_='unique')

    with op.batch_alter_table('dim_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dim_location_state'))
        batch_op.drop_index(batch_op.f('idx_dim_location_us_region'))

    with op.batch_alter_table('dim_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dim_time_season'))
        batch_op.drop_index(batch_op.f('idx_dim_time_time_of_day'))
        batch_op.drop_index(batch_op.f('idx_dim_time_year'))

    with op.batch_alter_table('dim_weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dim_weather_condition'))
        batch_op.drop_index(batch_op.f('idx_dim_weather_temp_bucket'))

    with op.batch_alter_table('fact_accident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fact_accident_accident_id'))
        batch_op.drop_index(batch_op.f('idx_fact_accident_location_id'))
        batch_op.drop_index(batch_op.f('idx_fact_accident_road_id'))
        batch_op.drop_index(batch_op.f('idx_fact_accident_time_id'))
        batch_op.drop_index(batch_op.f('idx_fact_accident_weather_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expires')
        batch_op.drop_column('reset_code')

    with op.batch_alter_table('fact_accident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fact_accident_weather_id'), ['weather_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fact_accident_time_id'), ['time_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fact_accident_road_id'), ['road_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fact_accident_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fact_accident_accident_id'), ['accident_id'], unique=False)

    with op.batch_alter_table('dim_weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dim_weather_temp_bucket'), ['temp_bucket'], unique=False)
        batch_op.create_index(batch_op.f('idx_dim_weather_condition'), ['weather_condition'], unique=False)

    with op.batch_alter_table('dim_time', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dim_time_year'), ['year'], unique=False)
        batch_op.create_index(batch_op.f('idx_dim_time_time_of_day'), ['time_of_day'], unique=False)
        batch_op.create_index(batch_op.f('idx_dim_time_season'), ['season'], unique=False)

    with op.batch_alter_table('dim_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dim_location_us_region'), ['us_region'], unique=False)
        batch_op.create_index(batch_op.f('idx_dim_location_state'), ['state'], unique=False)

    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_accident_id_clean'), ['accident_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
