"""add road features to AccidentRaw

Revision ID: 8eeb27dc0fc6
Revises: 5e6935bd55dd
Create Date: 2026-05-08 19:58:54.565446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eeb27dc0fc6'
down_revision = '5e6935bd55dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_accident_id_clean'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_accident_id_clean'), ['accident_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
