"""Add monitor jobs

Revision ID: 9d1809ba10ae
Revises: 008ff5192eee
Create Date: 2026-04-25 13:52:22.870426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1809ba10ae'
down_revision = '008ff5192eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etl_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etl_jobs', schema=None) as batch_op:
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('process_id')

    # ### end Alembic commands ###
