"""fix column names on etl  table

Revision ID: 9fc38b4bf05c
Revises: 03fa2f3a57f9
Create Date: 2026-04-19 13:54:38.868804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc38b4bf05c'
down_revision = '03fa2f3a57f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('visibility_km', sa.Float(), nullable=True))
        batch_op.drop_column('temperature')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('visibility_km')
        batch_op.drop_column('temperature_c')

    # ### end Alembic commands ###
