"""remove some attributes from fact that we dont need

Revision ID: ffa370c220bf
Revises: 9d1809ba10ae
Create Date: 2026-04-28 01:29:00.198459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffa370c220bf'
down_revision = '9d1809ba10ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_accident_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_accident_id_clean'), type_='unique')

    with op.batch_alter_table('accidents_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_raw_accident_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accidents_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_raw_accident_id'), ['accident_id'], unique=False)

    with op.batch_alter_table('accidents_clean', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_accident_id_clean'), ['accident_id'], postgresql_nulls_not_distinct=False)

    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('accident_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('predicted_severity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_accident_id'), ['accident_id'], unique=False)

    # ### end Alembic commands ###
